First tasks of TDD_Calculator
danil-polikanov/My.Homeworks pull request #12
Opened 2021-06-01 07:08 UTC by danil-polikanov

2021-06-25 11:58 UTC, danil-polikanov commented
Прошу проверить

2021-07-10 18:33 UTC, vladimir-shirmanov requested changes
> Прошу проверить

Так а что надо было проверять все мои коменты просто проигнорированы были и осталось все как и было. Именование тестов, класса, Assert.Pass на что надо было смотреть

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +    public class Tests
Именование

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +        public void Sum_null()
именование. чаще всего используется подход ИмяКласса_Метод_ПараметрыИОжидаемыйРезультат

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +            Assert.Pass();
Это еще что? для чего это здесь. Ты знаешь что оно делает?

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +        public void Sum_TwoNumbers()
ты не видишь противоречия тут TwoNumbers и "1,2,3,5"

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +            Assert.AreEqual(expected, actual);
Так а где исключение то?

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calculator.Tests/MyCalcTests.cs
> +    public class MyCalcTests
это что за муссор?

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calculator/StringCalculator.cs
> +                String[] lines = prepair.Split(new char[] { '\n', '\r', '!', '?', '.', ',' }, StringSplitOptions.RemoveEmptyEntries);
что это за рандомный список char?

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calculator/StringCalculator.cs
> +                    if (uint.TryParse(numArray[i].ToString(), out uint checkNegative))
что за пустой иф

2021-07-10 18:33 UTC, vladimir-shirmanov commented on TDD_Calculator/StringCalculator.cs
> +                        throw new Exception($"negatives not allowed: {negative.Where(x => x < 0).Select(x => x)}");
тут вообще какая то дичь

2021-07-10 18:34 UTC, closed without merging

2021-07-12 04:47 UTC, danil-polikanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +    public class Tests
К сожаление у меня не показывало ранние комментарии,сделал именования по примеру

2021-07-12 04:47 UTC, danil-polikanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +            Assert.Pass();
Убрал

2021-07-12 04:47 UTC, danil-polikanov commented on TDD_Calcluator.tests/UnitTest1.cs
> +            Assert.AreEqual(expected, actual);
Почему то смешались старая и новая версия,там проверка как раз на исключение и есть